#!/bin/bash

if [ -z $RCONDOR_HOST ]; then
  echo  "rcondor: \$RCONDOR_HOST not defined" >&2 
  exit 1
fi

conf=${HOME}/.rcondor/${RCONDOR_HOST}/rcondor.conf

if [ ! -f $conf ]; then
  echo "rcondor: config file does not exist: $conf" >&2  
  exit 1
fi

# parse config file
usr_host=`awk -F = '/^ *USR_HOST *=/ {print $2}' "$conf"`
usr_host=`echo $usr_host` # strip whitespaces
local=`awk -F = '/^ *LOCAL *=/ {print $2}' "$conf"`
local=`echo $local`
remote=`awk -F = '/^ *REMOTE *=/ {print $2}' "$conf"`
remote=`echo $remote`

# make sure config values are nonzero length
if [ -z "$usr_host" ] || [ -z "$local" ] || [ -z "$remote" ]; then
  echo "rcondor_mnt: error parsing rcondor.conf" >&2
  exit 1
fi

# use argument -u to unmount
if [ x$1 = x"-u" ]; then
  fusermount -u $local
  exit 0
fi

# check if remote disk is already mounted
ok=0
df -h $local | grep -q $RCONDOR_HOST && ok=1
if [ $ok = "1" ]; then
  echo "rcondor_mnt: remote disk already mounted on $local"
  exit 0
fi

# mount remote disk
echo "rcondor_mnt: mount remote disk on $local"
voms-proxy-info -exists
ret=$?
if [ $ret = 1 ] ; then
  echo Try again after having got a proxy
  exit 1
else
  mkdir -p $local
  sshfs "$usr_host:$remote" "$local" -o ssh_command=`which gsissh`
fi
